[project]
name = "horn-core"
version = "0.1.0"
description = "Core data structures for the horn simulation project."
dependencies = [
    "numpy"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
