[project]
name = "horn-core"
version = "0.1.0"
description = "Core data structures for the horn simulation project."
dependencies = [
    "numpy"
]

[project.scripts]
horn-candidates = "horn_core.candidates:main"

[project.optional-dependencies]
test = ["pytest"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
