[project]
name = "horn-solver"
version = "0.1.0"
description = "FEniCSx-based horn simulation and meshing."
dependencies = [
    "meshio",
    "pandas",
    "numpy",
    "mpi4py",
    "bempp-cl",
]

[project.scripts]
horn-solver = "horn_solver.solver:main"

[project.optional-dependencies]
test = [
    "pytest>=8.2.2"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build" 